language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
- sudo apt-get update
- git clone https://github.com/mpv-player/mpv-build.git
- cd mpv-build
- ./rebuild -j4
- sudo ./install
- cd ..
- sudo apt-get -qq install -y qt5-default make pkg-config qtdeclarative5-dev

script:
- mkdir build
- cd build
- qmake ../src/syncmpv.pro
- make
