language: cpp
compiler: gcc
sudo: required
  
before_install:
- sudo add-apt-repository ppa:mc3man/mpv-tests -y
- sudo apt-get -qq update
- sudo apt-get install mpv
- sudo apt-get -qq install -y qt5-default make pkg-config qtdeclarative5-dev

script:
- mkdir build
- cd build
- qmake ../src/syncmpv.pro
- make
