language: cpp
compiler: gcc
  
before_install:
- add-apt-repository ppa:mc3man/mpv-tests
- apt-get -qq update
- apt-get install mpv
- apt-get -qq install -y qt5-default make pkg-config qtdeclarative5-dev

script:
- mkdir build
- cd build
- qmake ../src/syncmpv.pro
- make
