language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
    - sudo add-apt-repository ppa:mc3man/testing6 -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install -y libmpv-dev
    - sudo apt-get -qq install -y qt5-default make pkg-config qtdeclarative5-dev

script:
    - mkdir build
    - cd build
    - qmake ../src/syncmpv.pro
    - make
