language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
- su
- apt-get -qq install -y gdebi
- wget "http://www.deb-multimedia.org/pool/main/m/mpv-dmo/mpv_0.23.0-dmo2_amd64.deb" -qO mpv.deb
- gdebi mpv.deb
- rm mpv.deb
- apt-get update
- apt-get install libmpv
- apt-get -qq install -y qt5-default make pkg-config qtdeclarative5-dev

script:
- mkdir build
- cd build
- qmake ../src/syncmpv.pro
- make
